"""new models for Order and Product

Revision ID: 1ef2ac8a1674
Revises: 9d419d776fc7
Create Date: 2024-02-21 02:38:28.900860

"""
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID
import uuid
from alembic import op

# revision identifiers, used by Alembic.
revision = '1ef2ac8a1674'
down_revision = '9d419d776fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
        sa.Column('id', sa.dialects.postgresql.UUID(as_uuid=False), primary_key=True, default=uuid.uuid4),
        sa.Column('name', sa.String(length=254), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('price', sa.Numeric(10, 2), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
        sa.Column('id', sa.dialects.postgresql.UUID(as_uuid=False), primary_key=True, default=uuid.uuid4),
        sa.Column('user_id', sa.dialects.postgresql.UUID(as_uuid=False), sa.ForeignKey('user.id'), nullable=False),
        sa.Column('product_id', sa.dialects.postgresql.UUID(as_uuid=False), sa.ForeignKey('product.id'), nullable=False),
        sa.Column('comments', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('product')
    # ### end Alembic commands ###
