"""trying to make the new user model work

Revision ID: 9d419d776fc7
Revises: 2530e177d0c6
Create Date: 2024-02-21 01:25:59.017384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9d419d776fc7"
down_revision = "2530e177d0c6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=254), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=254), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('name')
    ### end Alembic commands ###
